// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset.sql

package database

import (
	"context"
)

const clearUser = `-- name: ClearUser :exec
DELETE FROM users
`

func (q *Queries) ClearUser(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearUser)
	return err
}
